language: java
jdk:
  - oraclejdk8

before_install:
  - chmod ugo+x mvnw

addons:
    firefox: "44.0"

before_script:
- "sh -e /etc/init.d/xvfb start"
- "export DISPLAY=99:0"
- sleep 3 # give xvfb some time to start

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -Dmaven.javadoc.skip=true -B -V