language: java
sudo: false # faster builds
jdk:
  - oraclejdk8

before_install:
  - chmod ugo+x mvnw

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: true
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarqube:
    token:
      secure: "38a3100a525d157f7fe5f71a8753eb94e18e9e54"
  firefox: "44.0"
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar

script:
  - mvn clean install
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)